# Generated by Django 2.2.6 on 2020-04-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('password_hash', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=70, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(blank=True, max_length=250, null=True)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_v0.User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_start_time', models.DateTimeField(null=True)),
                ('expected_completetion_time', models.DateTimeField(null=True)),
                ('actual_completetion_time', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(max_length=200)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v0.User')),
            ],
        ),
    ]
