# Generated by Django 2.2.6 on 2020-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_completetion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_completetion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_time',
            field=models.DateField(null=True),
        ),
    ]
