# Generated by Django 2.2.6 on 2020-04-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0002_add_fields_admin_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
